name: pyturbo
channels:
  - conda-forge
dependencies:
  - cosapp
  - pyoccad
  - numpy
  - ambiance
  - pythermo
  - pythreejs
  - pytest
  - pre-commit
  - black
  - flake8
  - isort
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-autoapi
  - nbsphinx
  - sphinx_rtd_theme
  - pythonocc-core
  - ambiance
  - furo
  - nbsphinx-link
